params:
  dimension_table_1: restaurant_dim_table
  dimension_table_2: location_dim_table
  fact_table_1: fact_table
  columns_to_drop:
    - URL
    - PAGENO
  restaurant_columns:
    - NAME
    - CUSINE_CATEGORY
    - CUSINETYPE
    - TIMING
    - RATING_TYPE
  location_columns:
    - REGION
    - Latitude
    - Longitude
    - CITY
  fact_table_1_columns:
    - RATING
    - VOTES
    - PRICE
    - restaurant_id
    - location_id
  null_percentage_limit: 60
  dtype_mapping:
    object: 'TEXT'
    int64: 'INTEGER'
    float64: 'REAL'
    datetime64: 'TEXT'  # SQLite uses TEXT for date/time formats
    bool: 'INTEGER'     # SQLite doesn’t have a native boolean type, so we use INTEGER (0 or 1)
    category: 'TEXT'
    timedelta[ns]: 'TEXT'
